artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/iampraveens/Data-Hub/raw/main/telcoChurn.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/telcoChurn.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/telcoChurn.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preprocessing/cleaned_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib